POST http://localhost:3000/api/v1/adminModify/f6ebaeef-d5b0-4c69-bc78-2fc675902619
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI1ZmQ4MzFmMy05Y2NjLTQ5MmQtOGEzNi0wYjFjYzMxYzc5YTQiLCJpYXQiOjE3MjkyNTQwNzAsImV4cCI6MTcyOTI1NDY3MH0.iQIA9WPViOpeu2qh-K6lQHAVnpzF9R3oa2ZcJt0wacc

{
    "firstName": "NewFirstName",
    "lastName": "NewLastName",
    "birthDate": "",
    "address": "",
    "phone": "",
    "email": ""
}