POST http://localhost:3000/api/v1/recoveryPassword/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIyYTIzZDY0ZC0xMzJlLTQ0YWYtOTZlNS0wNmVhNWQwOTE4NGQiLCJpYXQiOjE3MjQ4Njg5ODgsImV4cCI6MTcyNDg2OTU4OH0.nCX1ZBW6bq3tYyi98Be5E-SPLYH3_zvDdNe5K7dh61g
content-type: application/json

{
    "password": "Erwin123*",
    "password2": "Erwin123*"
}