POST http://localhost:3000/api/v1/changePassword
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIyYTIzZDY0ZC0xMzJlLTQ0YWYtOTZlNS0wNmVhNWQwOTE4NGQiLCJpYXQiOjE3MjUwNjU1OTQsImV4cCI6MTcyNTA2NjE5NH0.nzXRKn0EL1naF0TJcHB4u822VshF7NQbRwXf56a-HZY

{
    "password": "<script>alert('XSS');</script>",
    "password2":"<script>alert('XSS');</script>"
}