POST http://localhost:3000/api/v1/modifyUser 
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIzNjNmN2MyNC1jZmQ3LTQxNDctYmI4NS0zMDY3OTI4ZmU4MjciLCJpYXQiOjE3MjE3NzQ2NTQsImV4cCI6MTcyMTc3NTI1NH0.uQ7UWMtSjIDHdOSkZV4f7_ntsqojzkmtl8AzLtc1OEU

{
"firstName": "1111111",
"lastName": "Barra",
"birthDate": "",
"address": "",
"phone": "",
"email": "",
"password": "",
"password2": ""
}
