POST http://localhost:3000/api/v1/modifyUser 
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJkZDc5N2EwNi0wOTU2LTQ2ZmQtYWJiNC0yOWE0ZGFkMjM4ODgiLCJpYXQiOjE3MjE0Mjk0ODIsImV4cCI6MTcyMTQzMDA4Mn0.n6BZM3cey9NXqNe6d2fH_IA3b9XpPrkpdusZSkehfms

{
"firstName": "",
"lastName": "Nuñez",
"birthDate": "",
"address": "",
"phone": "",
"email": "",
"password": "Erwin123*",
"password2": "Erwin123*"
}
